services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@gptdev:5432/chatdb
      - NODE_ENV=production
      - LLAMA_API_URL=http://llama:11434
      - LLAMA_MODEL=llama3
    depends_on:
      - llama
    extra_hosts:
      - "host.docker.internal:host-gateway"

  llama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: 